# Generated by Django 4.1.2 on 2023-07-27 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfavorites',
            old_name='favorites',
            new_name='favorite',
        ),
    ]
