# Generated by Django 4.1.2 on 2023-07-05 16:57

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=16)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('propertyType', models.CharField(blank=True, max_length=250, null=True)),
                ('bedrooms', models.IntegerField(blank=True, null=True)),
                ('bathrooms', models.IntegerField(blank=True, null=True)),
                ('furnishedType', models.CharField(blank=True, max_length=250, null=True)),
                ('listingDate', models.DateTimeField(blank=True, null=True)),
                ('petFriendly', models.CharField(blank=True, max_length=250, null=True)),
                ('smokers', models.CharField(blank=True, max_length=250, null=True)),
                ('gardens', models.CharField(blank=True, max_length=250, null=True)),
                ('parking', models.CharField(blank=True, max_length=250, null=True)),
                ('deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('letAvailableDate', models.DateTimeField(blank=True, null=True)),
                ('point_geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'properties',
            },
        ),
    ]
