# Generated by Django 4.1.2 on 2023-07-16 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_property_slug_alter_property_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='imageId',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
