# Generated by Django 4.1.2 on 2023-07-16 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_image_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='propertyUrl',
            field=models.URLField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
